/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class demoConstants {

  public static final boolean bDefault = true;

  public static final int iSmall = 1;

  public static final long iBig = 1L;

  public static final double dBig = (double)1;

  public static final String demo = "demo";

}
